name: publish npm

on: 
  push:
    #
    #
    #
    tags:
      - '**'
  
jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: pnpm i
      - run: pnpm build

      - run: pnpm site:build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTO_TOKEN }}